package com.example.apicallingdemo.model

data class VehicleSummary(
    val ALERT: String,
    val AVGSPEED: String,
    val COMPANY: String,
    val IDELTIME: String,
    val INACTIVETIME: String,
    val MAXSPEED: String,
    val RUNNINGDISTANCE: Int,
    val RUNNINGTIME: String,
    val SPEEDUNIT: String,
    val STOPTIME: String,
    val VEHICLE_ID: String,
    val VEHICLE_NUMBER: String,
    val VEHICLE_TYPE: String,
    val cvinfo1: String,
    val cvinfo2: String,
    val cvinfo3: String,
    val cvinfo4: String,
    val cvinfo5: String,
    val distance_cost: String,
    val distance_unit: String,
    val driver: String,
    val duration_cost: String,
    val end_location: String,
    val end_odometer: Int,
    val object_brand: String,
    val object_model: String,
    val start_location: String,
    val start_odometer: Int,
    val toll_cost: Int,
    val work_duration: String,
    val working_days: String
)